name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile code
        run: make


